### PR TITLE
Updates learning basics samples for 4.0

### LINKED ISSUE #365: Learning-basics broken
Hi, 

It seems that the Learning-basics module has not been updated to hazelcast-4.0 snapshot.

The learning-basics module configuration files still rely on the 3.11 configuration schema

```
<hazelcast xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
                               http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd"
           xmlns="http://www.hazelcast.com/schema/config">
[...]
</hazelcast>
```

Running the learning examples as-is leads to an XML exception (considering that the schemas don't match).
Upgrading the versions in the XML files does not work as there seems to be some breaking changes in the configuration schema.

- Downgrading the learning basics module to version 3.11 in the POM leads to another exception being thrown.
```
Caused by: java.lang.IllegalStateException: Unable to get `original` field in `HazelcastInstanceProxy`!
	at com.hazelcast.examples.helper.CommonUtils.<clinit>(CommonUtils.java:49)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: com/hazelcast/instance/impl/HazelcastInstanceProxy
	at com.hazelcast.examples.helper.CommonUtils.<clinit>(CommonUtils.java:46)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.hazelcast.instance.impl.HazelcastInstanceProxy
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
```

In the meantime I guess I'll check out a previous commit that still uses version 3.XX to get familiar with Hazelcast.

### PR DESCRIPTION
**Pull request by vbekiaris**
Fixes #365

### CODE REVIEW

**Comment by tezc** [comment]
Apparently build is broken after https://github.com/hazelcast/hazelcast/commit/fbca5a3bedcf8d0bb4b13bd5ae690ac794ee538d
